sequenceDiagram
    User->>Agent: gesture
    Note right of User: Gesture sources: Mouse, BCI, TouchSurface, SpaceNavigator, etc.
    Note over Agent: Grabber collection
    %loop update
        Agent->>Grabber: bogusEvent
    %end
    opt checkIfGrabsInput
        Grabber-->>Agent: grabber
    end
    Note over Agent,Grabber: inputGrabber = trackedGrabber != null ? trackedGrabber : defaultGrabber
    opt enqueue
        Agent-->>InputHandler: < bogusEvent, inputGrabber >
    end
    loop dequeue
      InputHandler->>Grabber: bogusEvent
    end
    Note over Grabber: performInteraction(bogusEvent)
