sequenceDiagram
    User->>InputHandler: gesture
    Note right of User: Gesture sources: Mouse, BCI, TouchSurface, SpaceNavigator, etc.
    Note over InputHandler: Agent collection
    opt updateTrackedGrabberFeed
        InputHandler-->>Agent: gesture
    end
    Note over Agent: Grabber collection
    %loop updateTrackedGrabber
        Agent->>Grabber: bogusEvent
    %end
    opt checkIfGrabsInput
        Grabber-->>Agent: grabber
    end
    Note over Agent,Grabber: inputGrabber = trackedGrabber != null ? trackedGrabber : defaultGrabber
    opt handleFeed
        InputHandler-->>Agent: gesture
    end
    opt enqueue
        Agent-->>InputHandler: < bogusEvent, inputGrabber >
    end
    loop dequeue
      InputHandler->>Grabber: bogusEvent
    end
    Note over Grabber: performInteraction(bogusEvent)

    %%Note over InputHandler: Agent collection
